dell/OpenManage-Enterprise

- Scripts/PowerShell/Get-IdentityPoolUsage.ps1
- Scripts/PowerShell/New-Network.ps1
- Scripts/Python/create_network.py
- Scripts/Python/get_identitypool_usage.py
Tested against OME 3.3.1 and OMEM 1.10.10.
Powershell and python scripts to parse a CSV file and create Network object for each row. Row headers are required and detailed in the script's help output. 
Also modified Identity Pool scripts to cleanup created sessions and removed a debug message.
> Added scripts to create Networks from CSV

- Scripts/Python/update_firmware_using_catalog.py
Have also removed all the dead code from this file. Hence the churn.
> Prior online catalog and associated baseline deleted based on --force switch

- Core/Python/create_network.py
- Core/Python/create_static_group.py
- Core/Python/get_device_list.py
- Core/Python/get_group_list.py
- Core/Python/get_identitypool_usage.py
- Core/Python/get_report_list.py
- Username should not be a required field because a default username of "admin" is already provided.
> Fix minor bug - username should not be required

- Core/Python/add_device_to_static_group.py
- Core/README.md
- If you Google OpenManage API you get very out of date documentation which leads you to believe the API is limited when in reality it can do a whole lot of things. Adding a link to the current reference will redirect people to the correct resources for implementation.
> README.md: Updating with current API reference

- Core/Python/add_device_to_static_group.py
- Added a python example of how to add an existing device in OME to a static group
> add_device_to_static_group.py: Example of adding device to group

- Core/Python/get_group_list.py
- Core/README.md
- README.md
- get_group_list.py: Rev'd version number and updated the code to account for pagination
- README.md: Shamelessly added myself to the contributor list
- Fixes https://github.com/dell/OpenManage-Enterprise/issues/30
> get_group_list.py: Update to account for pagination

- Core/PowerShell/Set-PowerState.ps1
- Core/PowerShell/Set-SystemConfiguration.ps1
- Core/PowerShell/Update-FirmwareUsingCatalog.ps1
- Core/PowerShell/Update-InstalledFirmware.ps1
- Core/Python/get_device_list.py
- Core/Python/set_power_state.py
- Core/Python/set_system_configuration.py
- Core/Python/update_firmware_using_dup.py
1. Device pagination issue fixed in Python and PowerShell scripts.
2. Removed request module dependency from get_device_list.py
> Device pagination issue fixed in Python and poweshell scripts.

- Core/PowerShell/Get-AuditLogs.ps1
- Core/Python/get_audit_logs.py
- Resolves #54 "Need a script to get audit logs and purge them weekly"
- Adds Get-AuditLogs.ps1 and get_audit_logs.py
- I did not see a way to purge the logs from the server. This may need to be resolved separately.
> #54 Get Audit Logs

- Core/PowerShell/Get-FirmwareBaselines.ps1
- Core/Python/get_firmware_baselines.py
- Added a script to pull a list of firmware baselines available on the server or pull baselines specific to a particular hast.
- Addresses #53
> get_firmware_baselines python/powershell

- Core/Python/add_device_to_static_group.py
- Core/Python/create_static_group.py
- Core/Python/refresh_device_inventory.py
- This script performs a manual, forced, refresh of a device's inventory.
- Addresses #58 "Need a script to initiate configuration inventory".
- create_static_group.py: Updates it to comply with pep484/8
- add_device_to_static_group.py: minor description update. Now matches other files.
> refresh_device_inventory.py: Added a script to perform inventory refresh

- Core/PowerShell/Invoke-DiscoverDevice.ps1
- Core/Python/invoke_discover_device.py
- Functionality left unchanged other than making it so track_job_to_completion would return true or false. This was done so that I could reuse that code elsewhere without change.
> discovery_device.py: Updated discover_device.py to be PEP484 compliant

- Core/Python/new_network.py
- new_network.py: Updated to match New-Network.ps1
> Renamed create_network.py to new_network.py

- CONTRIBUTING.md
- docs/powershell_library_code.md
- docs/python_library_code.md
- Added information on using odata filters in the contributor's guide
- Fixed a minor bug in the library code for Get-Data
- Expanded the PowerShell library code
> Update contributor guide and library code

- Core/PowerShell/Invoke-RefreshInventory.ps1
- Addresses issue #45 and creates a PowerShell parity to invoke_refresh_inventory.py
Signed-off-by: Grant Curell grant_curell@dell.com
> Invoke-RefreshInventory.ps1

- CONTRIBUTING.md
- Core/PowerShell/Update-InstalledFirmwareWithDup.ps1
- Core/Python/update_installed_firmware_with_dup.py
- Renamed update_installed_firmware.py to update_installed_firmware_using_dup.py
- Renamed Update-InstalledFirmware.ps1 to Update-InstalledFirmwareWithDup.ps1
- CONTRIBUTING.md: Updated guidelines for naming PowerShell variables
Signed-off-by: Grant Curell grant_curell@dell.com
> Updated name of update_installed_firmware

- Core/Python/get_group_list.py
- Core/Python/start_inventory_job.py
- Plugins/Power Manager/Alerts & Reports/Python/get_power_manager_alerts.py
- Plugins/Power Manager/Alerts & Reports/Python/get_power_manager_reports.py
- Plugins/Power Manager/Devices & Monitoring List/PowerShell/Find_non_PMP_capable_devices.ps1
- Plugins/Power Manager/Devices & Monitoring List/PowerShell/Find_non_Power_policy_capable_devices.ps1
- Plugins/Power Manager/Devices & Monitoring List/Python/Find_non_PMP_capable_devices.py
- Plugins/Power Manager/Devices & Monitoring List/Python/Find_non_Power_policy_capable_devices.py
- Plugins/Power Manager/Devices & Monitoring List/Python/get_power_manager_capable_devices.py
- Plugins/Power Manager/Devices & Monitoring List/Python/get_power_manager_monitoring_list.py
- Plugins/Power Manager/Metrics & Monitoring/Python/get_power_manager_device_metrics.py
- Plugins/Power Manager/Metrics & Monitoring/Python/get_power_manager_group_metrics.py
- Plugins/Power Manager/Metrics & Monitoring/Python/get_power_manager_top_energy_consumers.py
- Plugins/Power Manager/Metrics & Monitoring/Python/get_power_manager_top_offenders.py
- Plugins/Power Manager/Misc Scripts/PowerShell/Refresh_Inventory.ps1
- Plugins/Power Manager/Misc Scripts/Python/Perform_refresh_inventory.py
- Plugins/Power Manager/Misc Scripts/Python/get_set_power_manager_setting.py
- Plugins/Power Manager/Policy & EPR/Python/get_power_manager_EPR.py
- Plugins/Power Manager/Policy & EPR/Python/get_power_manager_policies.py
- Fixed irregular spacing on argparse declaration
- MUTEX_GROUP changed to mutex_group
- Changed instances of exclusive_group to mutex_group
- Standardized all variable names to fit this pattern: lower_case_with_underscores
- set_power_state.py: Fixed a bug where ip_address was not correctly capitalized to match IP_ADDRESS
- set_system_configuration.py: Fixed a bug where ip_address was not correctly capitalized to match IP_ADDRESS
- All files: Updated license to 2020
- Addresses part of #62 - Most Python code is not compliant with PEP8 and PEP484
- Changed all instances of Catch to catch
- Changed all instances of Finally to finally
- Ran Microsoft's Powershell formatter on all files
- Removed version numbers as no one is maintaining them and they are a copy-paste holdover from repo …
> #62 pep8 plugins update

- README.md
> README.md: Fix type-o

- Core/Python/invoke_refresh_inventory.py
- docs/API.md
- docs/API.md.j2
- Added a warning about All Devices for the invoke_refresh_inventory.py script (#58)
- Updated the API docs with current PDF
> #58-invoke_refresh_inventory.py - add warning

- Core/Python/get_alerts.py
- Core/Python/get_audit_logs.py
- Core/Python/get_firmware_baselines.py
- Core/Python/invoke_refresh_inventory.py
- Core/Python/set_power_state.py
- docs/python_library_code.md
- Fixed #106
- Improved error handling in the get_data function
- Fixed a minor bug in get_devices which caused it to not report failures properly
- Partially addresses #87 
> Fixed two minor bugs

- Core/Python/add_device_to_static_group.py
- Core/Python/get_device_list.py
- Core/Python/get_firmware_baselines.py
- Core/Python/invoke_refresh_inventory.py
- Core/Python/set_power_state.py
- Core/Python/update_firmware_using_catalog.py
- Core/Python/update_installed_firmware_with_dup.py
- Fixed a missing import in get_firmware_baselines.py
- Ran an import cleanup
- Ran code reformatting
- Fixed minor bug in update_firmware_using_catalog.py where it was missing a format string
> get_firmware_baselines.py: Fixed missing import

- Core/Python/add_device_to_static_group.py
- Core/Python/add_members.py
- Core/Python/edit_discovery_job.py
- Core/Python/get_alerts.py
- Core/Python/get_audit_logs.py
- Core/Python/get_chassis_inventory.py
- Core/Python/get_device_inventory.py
- Core/Python/get_device_list.py
- Core/Python/get_firmware_baselines.py
- Core/Python/get_group_details.py
- Core/Python/get_group_details_by_filter.py
- Core/Python/get_group_list.py
- Core/Python/get_identitypool_usage.py
- Core/Python/get_report_list.py
- Core/Python/invoke_discover_device.py
- Core/Python/invoke_refresh_inventory.py
- Core/Python/invoke_report_execution.py
- Core/Python/invoke_retire_lead.py
- Core/Python/new_mcm_group.py
- Core/Python/new_network.py
- Core/Python/new_static_group.py
- Core/Python/set_power_state.py
- Core/Python/set_system_configuration.py
- Core/Python/update_firmware_using_catalog.py
- Core/Python/update_installed_firmware_with_dup.py
- docs/CONTRIBUTING.md
Pulled commit over from https://github.com/dell/OpenManage-Enterprise/pull/123 and fixed conflicts. Committing here. Thanks to @5nafu for the code
> Add get pass

- Core/Python/invoke_manage_query_groups.py
> invoke_manage_query_groups.py: Fixed type-o in the examples

- Core/Python/set_power_state.py
> set_power_state.py: Fix bug causing group to default to all devices

- Core/Python/add_device_to_static_group.py
- Core/Python/invoke_discover_device.py
- Core/Python/invoke_refresh_inventory.py
- Core/Python/set_power_state.py
- docs/python_library_code.md
- This is in regards to #132. While it does not address the issue it does provide the user feedback as to what the problem is.
> invoke_discover_device.py: Add error handling response message

- README.md
- This message is no longer needed
> README.md: Remove message

- README.md
- docs/translations/README_zh.md
- docs/translations/README_zh_TW.md
- Added a translation of the READMEs in Chinese
> Added Chinese translations

- Core/PowerShell/New-OmeUser.ps1
- docs/API.md
- docs/categories.yml
> API.md: Updated docs to include New-OmeUser

- Core/PowerShell/Get-OmeUsers.ps1
- docs/API.md
- docs/categories.yml
- Added new script for getting a list of all users on OME
- Completes #47
> Get-OmeUser.ps1

- Core/Python/deploy_template.py
- Corrected an uh-oh oopsie. (It's the throw away one I use so it's not a big deal)
> deploy_template.py: Fixed error

- Core/PowerShell/Copy-Vlans.ps1
- Core/Python/copy_vlans.py
- Core/Python/get_alerts.py
- docs/API.md
- docs/categories.yml
- Addresses #51
- Adds both a Python and a PowerShell script for replicating VLANs between OME instances
> #51 - copy_vlans: Adds a script for replicating VLANs

- Core/PowerShell/Set-PowerState.ps1
- Core/Python/set_power_state.py
- docs/powershell_library_code.md
- Addresses #60, #63, and #56 for Set-PowerState.ps1
- Fixed spacing in the PowerShell library code and added some additional information for working with CSVs
> 56 PowerShell script to set power state on multiple devices / group ID and dump final result in a table or csv

- Core/PowerShell/Invoke-DiscoverDevice.ps1
- docs/API.md
- Invoke-DiscoveryDevice.ps1 now will display the number of devices successfully discovered at the end of execution.
> Invoke-DiscoverDevice.ps1: Updated code to display successful devices

- docs/generate_docs.py
Changed FullLoader to SafeLoader for loading YAML file
For More Info : https://www.exploit-db.com/docs/english/47655-yaml-deserialization-attack-in-python.pdf?utm_source=dlvr.it&utm_medium=twitter
Thanks and Regards Abhiram V
> Safe Implementation for Loading YAML

- docs/CONTRIBUTING.md
> CONTRIBUTING.md: Minor type-o fix

- Core/Python/get_chassis_profile.py
- Core/Python/get_identitypool.py
- Core/Python/get_identitypool_usage.py
- Core/Python/get_network.py
- Core/Python/get_template.py
- Core/Python/new_identitypool.py
- Core/Python/new_network.py
- Core/Python/new_template.py
- Core/Python/set_chassis_profile.py
- Core/Python/set_template_identitypool.py
- Core/Python/set_template_vlan.py
Modified
new_network.py
get_identitypool_usage.py
Added
get_chassis_profile.py
get_identitypool.py
get_network.py
get_template.py
new_identitypool.py
new_template.py
set_chassis_profile.py
set_template_identitypool.py
set_template_vlan.py
Signed-off-by: Trevor Squillario <Trevor.Squillario@Dell.com>
> MX python scripts

- Core/PowerShell/Add-DeviceToStaticGroup.ps1
- Core/PowerShell/Copy-Vlans.ps1
- Core/PowerShell/Get-Alerts.ps1
- Core/PowerShell/Get-AuditLogs.ps1
- Core/PowerShell/Get-DeviceList.ps1
- Core/PowerShell/Get-FirmwareBaselines.ps1
- Core/PowerShell/Get-OmeUsers.ps1
- Core/PowerShell/Invoke-DiscoverDevice.ps1
- Core/PowerShell/Invoke-RefreshInventory.ps1
- Core/PowerShell/New-OmeUser.ps1
- Core/PowerShell/Set-PowerState.ps1
- Core/PowerShell/Update-FirmwareUsingCatalog.ps1
- Core/Python/add_device_to_static_group.py
- Core/Python/copy_vlans.py
- Core/Python/deploy_template.py
- Core/Python/get_alerts.py
- Core/Python/get_audit_logs.py
- Core/Python/get_firmware_baselines.py
- Core/Python/invoke_discover_device.py
- Core/Python/invoke_manage_query_groups.py
- Core/Python/invoke_refresh_inventory.py
- Core/Python/set_power_state.py
- docs/powershell_library_code.md
- docs/python_library_code.md
- Patches the issue as seen in #161
- Update Python library code to display syntax highlighting
> 161 get-devicelist.ps1 error line 231 invoking the get-data function

- Core/Python/get_chassis_profile.py
- Core/Python/get_identitypool_usage.py
- Core/Python/get_template.py
- Core/Python/new_identity_pool.py
- Core/Python/new_template.py
- Core/Python/set_chassis_profile.py
- Core/Python/set_template_identity_pool.py
- Core/Python/set_template_vlan.py
- docs/categories.yml
Adds the following:
- get_chassis_profile.py
- get_identitypool_usage.py
- get_template.py
- new_identity_pool.py
- new_template.py
- set_chassis_profile.py
- set_template_identity_pool.py
- set_template_vlan.py
Categories has already been updated accordingly
> Add new MX7000 scripts

- README.md
> README.md: added explanation for the devel branch

- Core/PowerShell/Get-ReportList.ps1
- Core/PowerShell/Update-FirmwareUsingCatalog.ps1
- Core/Python/update_firmware_using_catalog.py
update_firmware_using_catalog:
- Fixed a minor bug where the repo type was required but shouldn't have been
Update-FirmwareUsingCatalog.ps1:
- Fixed the same bug and shamelessly added myself as an author since I rewrote the entire thing.
Get-ReportList.ps1:
- Fixed #176
- Addressed #60 and #63 for Get-ReportList.ps1
> Get-ReportList.ps1: Address #176

- docs/CONTRIBUTING.md
> CONTRIBUTING.md: Fix broken links

- Core/PowerShell/Add-DeviceToStaticGroup.ps1
- Core/PowerShell/Copy-Vlans.ps1
- Core/PowerShell/Get-Alerts.ps1
- Core/PowerShell/Get-AuditLogs.ps1
- Core/PowerShell/Get-FirmwareBaselines.ps1
- Core/PowerShell/Get-OmeUsers.ps1
- Core/PowerShell/Get-ReportList.ps1
- Core/PowerShell/Invoke-DiscoverDevice.ps1
- Core/PowerShell/Invoke-RefreshInventory.ps1
- Core/PowerShell/Set-PowerState.ps1
- Core/PowerShell/Update-FirmwareUsingCatalog.ps1
- README.md
- docs/CONTRIBUTING.md
- Updated the README to indicate that PS7 is a hard requirement
- Updated new PS scripts to carry with them a requirement that stops users from attempting to run  them if they do not have PS7
- Addresses #179
> Added PS7 as a requirement

- Core/PowerShell/Add-DeviceToStaticGroup.ps1
- Core/PowerShell/Copy-Vlans.ps1
- Core/PowerShell/Get-Alerts.ps1
- Core/PowerShell/Get-AuditLogs.ps1
- Core/PowerShell/Get-FirmwareBaselines.ps1
- Core/PowerShell/Get-OmeUsers.ps1
- Core/PowerShell/Get-ReportList.ps1
- Core/PowerShell/Invoke-DiscoverDevice.ps1
- Core/PowerShell/Invoke-RefreshInventory.ps1
- Core/PowerShell/Invoke-ReportExecution.ps1
- Core/PowerShell/Set-PowerState.ps1
- Core/PowerShell/Update-FirmwareUsingCatalog.ps1
- Core/Python/get_chassis_profile.py
- Core/Python/get_identitypool_usage.py
- Core/Python/get_template.py
- Core/Python/new_identity_pool.py
- Core/Python/new_template.py
- Core/Python/set_chassis_profile.py
- Core/Python/set_template_identity_pool.py
- Core/Python/set_template_vlan.py
- Core/Python/update_firmware_using_catalog.py
- README.md
- docs/CONTRIBUTING.md
- docs/categories.yml
- docs/powershell_library_code.md
- docs/python_library_code.md
> Routine Update

- Core/PowerShell/Invoke-ReportExecution.ps1
- Core/Python/deploy_template.py
- Core/Python/get_firmware_baselines.py
- Core/Python/invoke_discover_device.py
- Core/Python/invoke_refresh_inventory.py
- Core/Python/set_power_state.py
- Core/Python/update_firmware_using_catalog.py
- docs/API.md
- docs/python_library_code.md
- Removed unused variables
- Added full Google docstring to all functions
- Updated everything to use library code
- Added the ability to use idrac IP, group name, and device name
- Removed requirement for mutual exclusivity among command line options
- Made it so users can provide more than one device as an argument
- Addressed #62 for this script
- Fixed a bug where device type was not retrieved correctly. It retrieved the device's actual name instead of the type name
- Made it so get_baseline_id uses a one line odata filter with get_data instead of an exhaustive search
- Removed the function check_response_type. It was checking whether a compliance report was present, but was bugged. It would loop over all devices and would return true if only one of them had a compliance report. …
> 21 update_firmware_using_catalog.py compatible with OME Ent ?

- Core/Python/new_template.py
- README.md
- docs/API.md
- docs/categories.yml
- docs/python_library_code.md
- added comments to all functions
- Updated file handling to use OS module
- Updated file handling to use with instead of a naked call
- Removed baseuri
- Made the template name optional
- Added additional user output
- Updated docs
- Addresses #184 for new_template.py
library code:
- added post functionality
readme.md
- Updated the readme with tips for writing your own code and added a note about feedback
> new_template.py

- Core/Python/new_template.py
> new_template.py: Remove superfluous description

- Core/PowerShell/Get-SupportassistCases.ps1
- Core/PowerShell/Set-PowerState.ps1
- Core/Python/get_supportassist_cases.py
- Core/Python/new_template.py
- docs/API.md
- docs/categories.yml
- docs/powershell_library_code.md
- Completed python and powershell versions of a script to retrieve SAE cases
- Updated API docs
- Fixed a minor bug in CSV output for Set-PowerState.ps1
- Updated library code for outputting to CSV
- Completes #138
> 138 Script for list of current cases and case status

- Core/Python/deploy_template.py
- Core/Python/invoke_discover_device.py
- Core/Python/invoke_refresh_inventory.py
- Core/Python/set_power_state.py
- Core/Python/update_firmware_using_catalog.py
- docs/python_library_code.md
- Under certain error conditions track_job_to_completion would not display error messages correctly
- Fixed track_job_to_completion in the Python library code. It was missing some exception handling.
> Patched a bug in track_job_to_completion

- Core/PowerShell/get_warranty_information.ps1
- Core/Python/get_warranty_information.py
- docs/powershell_library_code.md
- docs/python_library_code.md
- Made improvements to both PowerShell and Python library code for writing CSVs. You no longer have to specify the fields to output.
- Added a Python function for checking the validity of a filepath
- Added a PowerShell function to the library code for converting a PSObject to a HashTable
- Fixes #137
> 137 Warranty reports and the devices covered under ProSupport and ProSupport Plus

- Core/Python/copy_vlans.py
- docs/API.md
> copy_vlans.py: Fix header formatting

- Core/Python/add_device_to_static_group.py
- Core/Python/add_members.py
- Core/Python/deploy_template.py
- Core/Python/edit_discovery_job.py
- Core/Python/get_alerts.py
- Core/Python/get_audit_logs.py
- Core/Python/get_chassis_inventory.py
- Core/Python/get_device_inventory.py
- Core/Python/get_device_list.py
- Core/Python/get_firmware_baselines.py
- Core/Python/get_group_details.py
- Core/Python/get_group_details_by_filter.py
- Core/Python/get_group_list.py
- Core/Python/get_ome_vlans.py
- Core/Python/get_report_list.py
- Core/Python/get_supportassist_cases.py
- Core/Python/get_warranty_information.py
- Core/Python/invoke_discover_device.py
- Core/Python/invoke_manage_query_groups.py
- Core/Python/invoke_refresh_inventory.py
- Core/Python/invoke_report_execution.py
- Core/Python/invoke_retire_lead.py
- Core/Python/new_mcm_group.py
- Core/Python/new_network.py
- Core/Python/new_static_group.py
- Core/Python/new_template.py
- Core/Python/set_power_state.py
- Core/Python/update_firmware_using_catalog.py
- Core/Python/update_installed_firmware_with_dup.py
Fixed a problem where a user can have what's  called a "bad terminal". See https://stackoverflow.com/a/58277159/4427375. I patched it so if they have a terminal where getpass wouldn't work they will instead receive a prompt.
> getpass update

- PowerShell/README.md
- Python/README.md
- Python/get_power_manager_epr.py
- Python/invoke_refresh_power_manager_inventory.py
- docs/API.md
> Minor documentation fix

- Python/set_power_state.py
- docs/python_library_code.md
> 204 set_power_state.py errors out if the power state for a box is already set to the requested

- Python/update_firmware_using_catalog.py
- Fixes #218
- Fixes a bug with using Dell online repos
> 218 Add ability to stage for next reboot to firmware update scripts

- Python/invoke_refresh_inventory.py
- Fixed an issue where the user was permitted to input an invalid configuration. It now correctly issues an error message when encountering the problem.
> invoke_refresh_inventory.py: Added guard

- PowerShell/Get-Alerts.ps1
- PowerShell/README.md
- Python/README.md
- Python/get_alerts.py
- docs/API.md
- Fixes #101
- Fixed type-o
- Updated documentation
- Added timestamp functionality for both python and powershell versions
> 101 It is unclear how to filter using timestamp in the alerts API (potentially not working?)

- Python/update_firmware_using_catalog.py
- Fixed a bug in the new feature which allows you to control sleep and wait times. If you did not provide one it defaulted to None which caused an error in the job wait.
> update_firmware_using_catalog.py: Minor bug fix

- README.md
- docs/API.md
> Fixed broken API docs link and updated readme

- Python/deploy_template.py
- Python/invoke_discover_device.py
- Python/new_template.py
- Added --discoverType parameter to invoke_discover_device.py to allow discovering devices by REDFISH, IPMI or WSMAN
- Added --template-name parameter to deploy_template.py to deploy an existing template to device rather than from a source device
- Fixed job status polling in deploy_template.py
- Fixed non-unicode character error in new_template.py
> Python script updates

- Python/new_mcm_group.py
- Fixes #241
- Added member_devices to return.
> 241 new_mcm_group.py get_domains function not assigning members
